/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.ArrayList;
import java.util.List;
import model.bean.Global;
import model.bean.Perguntas;
import model.dao.PerguntasDAO;

/**
 *
 * @author Senai
 */
public class TelaTemas extends javax.swing.JFrame {

    /**
     * Creates new form TelaMenu
     */
    public TelaTemas() {
        initComponents();
        setTitle("Temas");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputTec = new javax.swing.JButton();
        inputEnt = new javax.swing.JButton();
        inputGeral = new javax.swing.JButton();
        inputCiencia = new javax.swing.JButton();
        inputEsportes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inputTec.setBackground(new java.awt.Color(0, 0, 255));
        inputTec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputTec.setForeground(new java.awt.Color(255, 204, 0));
        inputTec.setText("Tecnologia");
        inputTec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTecActionPerformed(evt);
            }
        });
        jPanel1.add(inputTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 250, 180, 40));

        inputEnt.setBackground(new java.awt.Color(0, 0, 255));
        inputEnt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputEnt.setForeground(new java.awt.Color(255, 204, 0));
        inputEnt.setText("Entretenimento");
        inputEnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEntActionPerformed(evt);
            }
        });
        jPanel1.add(inputEnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 180, 40));

        inputGeral.setBackground(new java.awt.Color(0, 0, 255));
        inputGeral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputGeral.setForeground(new java.awt.Color(255, 204, 0));
        inputGeral.setText("Gerais");
        inputGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputGeralActionPerformed(evt);
            }
        });
        jPanel1.add(inputGeral, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, 180, 40));

        inputCiencia.setBackground(new java.awt.Color(0, 0, 255));
        inputCiencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputCiencia.setForeground(new java.awt.Color(255, 204, 0));
        inputCiencia.setText("Ciência e Natureza");
        inputCiencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCienciaActionPerformed(evt);
            }
        });
        jPanel1.add(inputCiencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 250, 170, 40));

        inputEsportes.setBackground(new java.awt.Color(0, 0, 255));
        inputEsportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        inputEsportes.setForeground(new java.awt.Color(255, 204, 0));
        inputEsportes.setText("Esportes");
        inputEsportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEsportesActionPerformed(evt);
            }
        });
        jPanel1.add(inputEsportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 370, 170, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 204, 0));
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 620, 130, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ShowMenu.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputEntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEntActionPerformed
       carregarPerguntasPorCategoria(3);
    

    }//GEN-LAST:event_inputEntActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        }); dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void inputTecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTecActionPerformed
      
     carregarPerguntasPorCategoria(4);
        
    }//GEN-LAST:event_inputTecActionPerformed

    private void inputCienciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCienciaActionPerformed
       
       carregarPerguntasPorCategoria(2);
    }//GEN-LAST:event_inputCienciaActionPerformed

    private void inputEsportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEsportesActionPerformed
      
        
        carregarPerguntasPorCategoria(1);


    }//GEN-LAST:event_inputEsportesActionPerformed

    private void inputGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputGeralActionPerformed
       carregarPerguntasPorCategoria(5);



        
        
    }//GEN-LAST:event_inputGeralActionPerformed
private void carregarPerguntasPorCategoria(int categoriaId) {
    PerguntasDAO perguntasDAO = new PerguntasDAO();
    try {
        // Limpa a lista Global.getPerguntas()
        Global.setPerguntas(new ArrayList<>());
        Global.setNumeros(new ArrayList<>());

        // Perguntas do banco de dados
        List<Perguntas> perguntasPorCategoria = perguntasDAO.lerPorCategoria(categoriaId);

        // Adiciona as perguntas à variável global
        for (Perguntas pergunta : perguntasPorCategoria) {
            Global.getPerguntas().add(pergunta);
        }

        // Acessar perguntas
        List<Perguntas> perguntas = Global.getPerguntas();
        for (Perguntas pergunta : perguntas) {
            System.out.println(pergunta);
        }

        // Acessar tela de perguntas
        java.awt.EventQueue.invokeLater(() -> {
            new TelaPerguntas().setVisible(true);
        });

    } catch (Exception e) {
        e.printStackTrace(); // Log de erro
    }
    
    dispose(); // Fecha a janela atual após o clique no botão
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
    }


       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputCiencia;
    private javax.swing.JButton inputEnt;
    private javax.swing.JButton inputEsportes;
    private javax.swing.JButton inputGeral;
    private javax.swing.JButton inputTec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
