/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import model.bean.Global;
import model.bean.Usuarios;
import model.dao.UsuariosDAO;

/**
 *
 * @author Senai
 */
public class TelaLogin extends javax.swing.JFrame {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
         initComponents();
        setTitle("Login");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        inputLogin = new javax.swing.JTextField();
        inputEntrar = new javax.swing.JButton();
        inputcadastrar = new javax.swing.JButton();
        inputSenha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(inputLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 360, 70));

        inputEntrar.setBackground(new java.awt.Color(0, 0, 255));
        inputEntrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inputEntrar.setForeground(new java.awt.Color(255, 204, 0));
        inputEntrar.setText("Entrar");
        inputEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputEntrarActionPerformed(evt);
            }
        });
        jPanel1.add(inputEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 470, 360, 70));

        inputcadastrar.setBackground(new java.awt.Color(0, 0, 255));
        inputcadastrar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        inputcadastrar.setForeground(new java.awt.Color(255, 204, 0));
        inputcadastrar.setText("Cadastrar-se");
        inputcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputcadastrarActionPerformed(evt);
            }
        });
        jPanel1.add(inputcadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(853, 660, 220, 70));

        inputSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSenhaActionPerformed(evt);
            }
        });
        jPanel1.add(inputSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 370, 360, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ShowDoMilha.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputcadastrarActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        }); dispose();
    }//GEN-LAST:event_inputcadastrarActionPerformed

    private void inputSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSenhaActionPerformed

    private void inputEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputEntrarActionPerformed
       String loginVi = inputLogin.getText();
       String senhaV = inputSenha.getText();

if (loginVi.isEmpty() || senhaV.isEmpty()) {
    JOptionPane.showMessageDialog(null, "Preencha todos os campos.");
} else {
    UsuariosDAO usuariosDAO = new UsuariosDAO();
    Usuarios loginVteste = usuariosDAO.verificarLogin(loginVi, senhaV);
    Global.setId(loginVteste.getIdUsuario());
     
    if (loginVteste.getIdUsuario() > 0) {
        JOptionPane.showMessageDialog(null, "Login bem sucedido");
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaMenu().setVisible(true);
            }
        }); dispose();
    } else {
        // Senha incorreta ou usuário não encontrado
        JOptionPane.showMessageDialog(null, "Login ou senha inválidos.");
    }
}
    }//GEN-LAST:event_inputEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inputEntrar;
    private javax.swing.JTextField inputLogin;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JButton inputcadastrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
